name: Build

on:
  push:
    branches:
      - build

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      # Build Capacitor
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      - run: npx cap copy
      # Build Android
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: cd ${{ github.workspace }}/android
      - run: ./gradlew build
      # - uses: eskatos/gradle-command-action@v1
      #   with:
      #     build-root-directory: ./android
      #     arguments: build
      # Build Electron
      # - name: Build & Publish Electron
      #   run: npm run electron:publish
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
