name: Build project and Run Lighthouse CI
on:
  push:
    branch:
      - master

jobs:
  # BUILD APP
  build_angular:
    name: Build Angular
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache node modules
        id: npm_cache
        uses: actions/cache@preview
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
        if: steps.npm_cache.outputs.cache-hit != 'true'
      - run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  lighthouse_CI:
    name: Lighthouse CI
    needs: build_angular
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.3.x
          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
